export { IPokemonRepository } from './IPokemonRepository'
export { ITypeRepository } from './ITypeRepository'
export { IGenerationRepository } from './IGenerationReposity'
export { IWheaterRepository } from './IWheaterRepository'
export { IFamilyRepository } from './IFamilyRepository'